name: Auto Push ds-config.json
permissions:
  contents: write

on:
  schedule:
    - cron: '0 * * * *'  # 在每小时的00分和30分运行
  workflow_dispatch:  # 允许手动触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run config converting script
        run: python main.py

      - name: Push to config_convert repo
        run: |
          git clone https://x-access-token:${{ secrets.PAT }}@github.com/hyjump/config_convert.git pages-repo
          cp ds-config.json pages-repo/
          mkdir -p pages-repo/other-assets
          cp ds-config.json pages-repo/other-assets/
          cd pages-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add -f ds-config.json
          git add -f other-assets/ds-config.json
          git commit -m "Auto update ds-config.json" || echo "No changes to commit"
          git push
